# Copyright 2025 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

tasks:
  - name: all
    description: Create and deploy the base and IDAM layers of UDS Core to test that MetalLB lets traffic through
    actions:
      - cmd: |
          ./uds zarf package deploy oci://ghcr.io/defenseunicorns/packages/uds/core-base:0.34.1-upstream --confirm
          ./uds zarf package deploy oci://ghcr.io/defenseunicorns/packages/uds/core-identity-authorization:0.34.1-upstream --confirm
          # if curl -s https://sso.uds.dev | grep -q "Username"; then
          #   echo "Successfully hit Keycloak through MetalLB"
          # else
          #   echo "Failed to make a request to Keycloak through MetalLB"
          #   exit 1
          # fi
