# Copyright 2025 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

{{- if .Values.tenantIngress.ipAddressPool }}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: tenant-ingressgateway
  namespace: metallb-system
spec:
  addresses:
    - {{ .Values.tenantIngress.ipAddressPool }}/32
  serviceAllocation:
    priority: 50
    namespaces:
      - {{ .Values.tenantIngress.namespace }}
    serviceSelectors:
      - matchLabels:
          {{- toYaml .Values.tenantIngress.matchLabels | nindent 10 }}
{{- end }}
