# Copyright 2025 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

{{- if .Values.passthroughIngress.ipAddressPool }}
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: keycloak-ingressgateway
  namespace: metallb-system
spec:
  ipAddressPools:
    - keycloak-ingressgateway
  {{- if .Values.interface }}
  interfaces:
    - {{ .Values.interface }}
  {{- end }}
{{- end }}
